#!/usr/bin/env bash

TARGETDIR=localResults
BASEDIR=baseResults

while read t; do
    echo Running $t...
	b=`basename $t`
    ./glslangValidator.exe -i $t > $TARGETDIR/$b.out
    diff $BASEDIR/$b.out $TARGETDIR/$b.out
done < testlist
