#version 450 core

#extension GL_EXT_float_ue8m0 : require
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    floatue8m0_t zero = floatue8m0_t(0);
    floatue8m0_t c00000000 = floatue8m0_t(5.88e-39);
    floatue8m0_t c00000001 = floatue8m0_t(1.176e-38);
    floatue8m0_t c11111110 = floatue8m0_t(8.51e37);
    floatue8m0_t c11111111 = floatue8m0_t(1.71e38);
    floatue8m0_t inf = floatue8m0_t(1.0/0.0);
    floatue8m0_t neg = floatue8m0_t(-100);
    floatue8m0_t neg_inf = floatue8m0_t(-1.0/0.0);
}
