#version 450 core

#extension GL_EXT_float_e2m1 : require
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    {
        floate2m1_t c000_0 = 0.0fe2m1;
        floate2m1_t c000_1 = 0.5fe2m1;
        floate2m1_t c001_0 = 1.0fe2m1;
        floate2m1_t c001_1 = 1.5fe2m1;
        floate2m1_t c010_0 = 2.0fe2m1;
        floate2m1_t c010_1 = 3.0fe2m1;
        floate2m1_t c011_0 = 4.0fe2m1;
        floate2m1_t c011_1 = 6.0fe2m1;
    }
    {
        floate2m1_t c000_0 = floate2m1_t(0.0f);
        floate2m1_t c000_1 = floate2m1_t(0.5f);
        floate2m1_t c001_0 = floate2m1_t(1.0f);
        floate2m1_t c001_1 = floate2m1_t(1.5f);
        floate2m1_t c010_0 = floate2m1_t(2.0f);
        floate2m1_t c010_1 = floate2m1_t(3.0f);
        floate2m1_t c011_0 = floate2m1_t(4.0f);
        floate2m1_t c011_1 = floate2m1_t(6.0f);
        floate2m1_t c100_0 = floate2m1_t(-0.0f);
        floate2m1_t c100_1 = floate2m1_t(-0.5f);
        floate2m1_t c101_0 = floate2m1_t(-1.0f);
        floate2m1_t c101_1 = floate2m1_t(-1.5f);
        floate2m1_t c110_0 = floate2m1_t(-2.0f);
        floate2m1_t c110_1 = floate2m1_t(-3.0f);
        floate2m1_t c111_0 = floate2m1_t(-4.0f);
        floate2m1_t c111_1 = floate2m1_t(-6.0f);
    }
    const float f = 1.1;
    floate2m1_t c = floate2m1_t(f);
}
