#version 450 core

#extension GL_EXT_float_mxint8 : require
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    floatmxint8_t c00000000 = floatmxint8_t(0);
    floatmxint8_t c00000001 = floatmxint8_t(0.015625);
    floatmxint8_t c01000000 = floatmxint8_t(1);
    floatmxint8_t c01111111 = floatmxint8_t(2.0 - 0.015625);

    floatmxint8_t c11111111 = floatmxint8_t(-0.015625);
    floatmxint8_t c11000000 = floatmxint8_t(-1);
    floatmxint8_t c10000001 = floatmxint8_t(-(2.0 - 0.015625));

    floatmxint8_t inf = floatmxint8_t(1.0/0.0);
    floatmxint8_t neg_100 = floatmxint8_t(-100);
    floatmxint8_t neg_inf = floatmxint8_t(-1.0/0.0);
}
