#version 450 core

#extension GL_EXT_float_e5m2 : require
#extension GL_EXT_float_e2m1 : require
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_long_vector : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

const floate2m1_t bc10 = 10.fe2m1;
const fe2m1vec2 b2c10 = fe2m1vec2(bc10, bc10);
layout(constant_id = 1) const floate2m1_t bsc10 = 10.fe2m1;

struct S { floate2m1_t b; };
const S sc = S(bc10);

const floate2m1_t bca[2] = {bc10, bc10};

floate2m1_t funcfe2m1(floate2m1_t x)
{
    return x;
}

void main()
{
    float f = 2.0;
    floate2m1_t b = floate2m1_t(1.0fe2m1);

    floate5m2_t fe5m2 = floate5m2_t(7);
    float16_t f16 = float16_t(7);
    float32_t f32 = 7;
    float64_t f64 = 7;
    fe5m2 = floate5m2_t(b);
    f16 = float16_t(b);
    f32 = float32_t(b);
    f64 = float64_t(b);

    f16 = b;
    f32 = b;
    f64 = b;

    b = funcfe2m1(b);


    fe2m1vec2 v2;
    fe2m1vec4 v4;
    vector<floate2m1_t, 8> v8;
    vector<floate2m1_t, 16> v16;

    uint8_t u8 = packFloat2xfe2m1EXT(v2);
    uint16_t u16 = packFloat4xfe2m1EXT(v4);
    uint32_t u32 = packFloat8xfe2m1EXT(v8);
    u32vec2 u32v2 = packFloat16xfe2m1EXT(v16);

    v2 = unpackFloat2xfe2m1EXT(u8);
    v4 = unpackFloat4xfe2m1EXT(u16);
    v8 = unpackFloat8xfe2m1EXT(u32);
    v16 = unpackFloat16xfe2m1EXT(u32v2);

    b = bitcastExtractfe2m1EXT(uint8_t(1), 2);
    fe2m1vec4 v4_2 = bitcastExtractfe2m1EXT(u8vec4(1), 2);
    vector<floate2m1_t, 7> v7 = bitcastExtractfe2m1EXT(vector<uint8_t, 7>(1), 3);
}
