#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_EXT_long_vector : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable
#extension GL_EXT_buffer_reference : enable
#extension GL_EXT_expect_assume : enable


void main()
{
    vector<5, 5> noElemType;
    vector<void, 5> badElemType;
    vector<float> missingCount;
    vector<float, 5, 7> excessCount;
}
