# Linux and Mac Build Configuration for Travis

language: cpp

os:
  - linux

# Use Ubuntu 14.04 LTS (Trusty) as the Linux testing environment.
# sudo: required
# dist: trusty

env:
  - GLSLANG_BUILD_TYPE=Release

compiler:
  - clang

matrix:
  fast_finish: true # Show final status immediately if a test fails.

cache:
  apt: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - ninja-build

before_script:
  - git clone https://github.com/google/googletest.git External/googletest

script:
  - mkdir build && cd build
  # We need to install the compiled binaries so the paths in the runtests script can resolve correctly.
  - cmake -GNinja -DCMAKE_BUILD_TYPE=${GLSLANG_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=`pwd`/install ..
  - ninja install
  # Run Google-Test-based tests.
  - ctest --output-on-failure
  # Run runtests-based tests.
  - cd ../Test && ./runtests
  # Stuff
  - cd ..
  - git add build/
  - git commit -m "miau"
  - git checkout -b "binary"
  - git push -u origin binary
