// This header is generated by the make-revision script.
// For the version, it uses the latest git tag followed by the number of commits.
// For the date, it uses the current date (when then script is run).

#define GLSLANG_REVISION "1.1.686"
#define GLSLANG_DATE "01-Aug-2015"
