// This header is generated by the make-revision script.
// For the version, it uses the latest git tag followed by the number of commits.
// For the date, it uses the current date (when then script is run).

#define GLSLANG_REVISION "Overload400-PrecQual.1971"
#define GLSLANG_DATE "03-Apr-2017"
